[package]
name = "quotatide"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish = false
build = "build.rs"

[lib]
name = "quotatide_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
quota-core = { path = "../crates/quota-core", version = "=0.1.0" }
tauri = { version = "=2.11.5", features = ["image-png", "tray-icon"] }

[lints]
workspace = true
