// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One stable alert event configurable by the user.
 */
export type AlertEventKind = "daily80" | "daily100" | "weekly_remaining20" | "weekly_remaining10" | "radar_chance70" | "quota_reset_confirmed" | "source_failures3";
