// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Delivery channel for one alert event.
 */
export type AlertChannel = "system" | "email";
