// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Overview section associated with an alert or notification click.
 */
export type AlertTarget = "today" | "radar" | "source";
