// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One stable alert event configurable by the user.
 */
export type AlertEventKind = "daily_80" | "daily_100" | "weekly_remaining_20" | "weekly_remaining_10" | "radar_chance_70" | "quota_reset_confirmed" | "source_failures_3";
