// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertChannel } from "./AlertChannel";
import type { AlertEventKind } from "./AlertEventKind";

/**
 * Secret-free persisted alert preference.
 */
export type AlertPreference = { eventKind: AlertEventKind, channel: AlertChannel, enabled: boolean, };
