// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Public, non-secret metadata exposed by the desktop shell.
 */
export type BuildInfo = { productName: string, version: string, author: string, identifier: string, stage: string, };
