// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Small native event that tells the UI to re-query the dashboard projection.
 */
export type DashboardChanged = { revision: number, };
