// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-selected interface language. Formatting locale and policy timezone are
 * deliberately resolved independently by the presentation layer.
 */
export type InterfaceLocalePreference = "system" | "zh-CN" | "en";
