// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current operating-system notification authorization state.
 */
export type NotificationPermissionStatus = "unknown" | "granted" | "denied" | "error";
