// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One current SMTP recipient. Retired recipients are never returned.
 */
export type PublicSmtpRecipient = { address: string, enabled: boolean, };
