// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicLiveQuota } from "./PublicLiveQuota";

/**
 * Complete query result for the current dashboard projection.
 */
export type PublicLiveQuotaState = { dashboardRevision: number, refreshing: boolean, quota: PublicLiveQuota | null, };
