// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertEventKind } from "./AlertEventKind";
import type { AlertTarget } from "./AlertTarget";
import type { PublicDeliveryState } from "./PublicDeliveryState";

/**
 * Secret-free persisted reminder rendered by the current UI locale.
 */
export type PublicAlertEvent = { eventId: number, eventKind: AlertEventKind, localDate: string | null, source: string | null, target: AlertTarget, systemDeliveryState: PublicDeliveryState | null, createdAtUnixMs: number, };
