// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationPermissionStatus } from "./NotificationPermissionStatus";
import type { PublicAlertEvent } from "./PublicAlertEvent";

/**
 * In-app reminder projection and current notification authorization state.
 */
export type PublicAlertInbox = { notificationPermissionStatus: NotificationPermissionStatus, events: Array<PublicAlertEvent>, };
