// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current system-channel state displayed with one in-app reminder.
 */
export type PublicDeliveryState = "pending" | "delivered" | "retry_wait" | "paused_permission" | "failed";
