// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One read-only earned reset credit. Opaque identifiers are intentionally not exposed.
 */
export type PublicResetCredit = { status: string, expiresAtUnixS: number | null, };
