// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertPreference } from "./AlertPreference";
import type { InterfaceLocalePreference } from "./InterfaceLocalePreference";
import type { NotificationPermissionStatus } from "./NotificationPermissionStatus";
import type { PublicQuotaPolicy } from "./PublicQuotaPolicy";
import type { PublicSmtpSettings } from "./PublicSmtpSettings";

/**
 * Every non-secret setting returned as one revisioned projection.
 */
export type PublicSettings = { settingsRevision: number, configured: boolean, pathSummary: string | null, accountLabel: string | null, notificationPermissionStatus: NotificationPermissionStatus, quotaPolicy: PublicQuotaPolicy, alertPreferences: Array<AlertPreference>, autostartEnabled: boolean, autoUpdateEnabled: boolean, interfaceLocale: InterfaceLocalePreference, formatLocale: string, smtp: PublicSmtpSettings, };
