// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable error categories shared by the Rust application layer and IPC.
 */
export type PublicErrorCode = "invalid_path" | "auth_not_found" | "auth_permission_denied" | "auth_not_regular_file" | "auth_too_large" | "auth_invalid_utf8" | "auth_invalid_json" | "auth_unsupported_mode" | "auth_missing_access_token" | "auth_missing_account_id" | "auth_invalid_account_id" | "settings_conflict" | "storage_unavailable";
