// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertPreference } from "./AlertPreference";
import type { PublicQuotaPolicy } from "./PublicQuotaPolicy";

/**
 * Every non-secret setting returned as one revisioned projection.
 */
export type PublicSettings = { settingsRevision: number, configured: boolean, pathSummary: string | null, accountLabel: string | null, quotaPolicy: PublicQuotaPolicy, alertPreferences: Array<AlertPreference>, autostartEnabled: boolean, };
