// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicResetCredit } from "./PublicResetCredit";

/**
 * Secret-free, independently fetched reset-credit snapshot.
 */
export type PublicResetCredits = { availableCount: number, credits: Array<PublicResetCredit>, checkedAtUnixMs: number, };
