// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable burn projection derived from recent observations in one quota window.
 */
export type PublicBurnProjection = { sampleCount: number, observedSpanSeconds: number, rateMicropointsPerHour: number, projectedUsedAtResetMicropoints: number, exhaustsAtUnixS: number | null, };
