// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicSmtpRecipient } from "./PublicSmtpRecipient";
import type { SmtpCredentialStatus } from "./SmtpCredentialStatus";
import type { SmtpTlsMode } from "./SmtpTlsMode";

/**
 * Secret-free SMTP settings projection.
 */
export type PublicSmtpSettings = { enabled: boolean, host: string, port: number, tlsMode: SmtpTlsMode, username: string, fromAddress: string, fromName: string, recipients: Array<PublicSmtpRecipient>, credentialStatus: SmtpCredentialStatus, };
