// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stable, secret-free account configuration projection for the UI.
 */
export type PublicAccountSettings = { settingsRevision: number, configured: boolean, pathSummary: string | null, accountLabel: string | null, };
