// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceFreshness } from "./SourceFreshness";
import type { UsageSourceErrorCode } from "./UsageSourceErrorCode";

/**
 * Secret-free live quota projection returned by the application query.
 */
export type PublicLiveQuota = { usedMicropoints: number | null, remainingMicropoints: number | null, capturedAtUnixMs: number | null, resetsAtUnixS: number | null, planType: string | null, allowed: boolean | null, lastAttemptAtUnixMs: number, lastSuccessAtUnixMs: number | null, consecutiveFailures: number, freshness: SourceFreshness, publicError: UsageSourceErrorCode | null, };
