// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicRadarAnnouncement } from "./PublicRadarAnnouncement";
import type { PublicRadarPrediction } from "./PublicRadarPrediction";
import type { RadarSourceErrorCode } from "./RadarSourceErrorCode";
import type { SourceStatus } from "./SourceStatus";

/**
 * Secret-free Radar projection. Its health is independent from Codex usage.
 */
export type PublicResetRadar = { lastAttemptAtUnixMs: number | null, lastSuccessAtUnixMs: number | null, consecutiveFailures: number, sourceStatus: SourceStatus, publicError: RadarSourceErrorCode | null, prediction: PublicRadarPrediction | null, latestAnnouncement: PublicRadarAnnouncement | null, };
