// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerDayStatus } from "./LedgerDayStatus";

export type PublicLedgerDay = { localDate: string, usedMicropoints: number | null, policyRevision: number, policyTimezone: string, baseMicropoints: number, carryMicropoints: number, limitMicropoints: number, isToday: boolean, finalized: boolean, status: LedgerDayStatus, };
