// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current immutable daily-policy revision exposed without account secrets.
 */
export type PublicQuotaPolicy = { policyRevision: number, policyTimezone: string, carryWorkdaysEnabled: boolean, baseMicropoints: Array<number>, };
