// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicErrorCode } from "./PublicErrorCode";
import type { SafeErrorContext } from "./SafeErrorContext";

/**
 * The only account-configuration error payload allowed across IPC.
 */
export type PublicError = { code: PublicErrorCode, messageKey: string, safeContext: SafeErrorContext, };
