// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerDayStatus } from "./LedgerDayStatus";

export type PublicLedgerDay = { localDate: string, usedMicropoints: number | null, limitMicropoints: number | null, isToday: boolean, status: LedgerDayStatus, };
