// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-facing pressure state for the current weekly quota chamber.
 */
export type QuotaPressure = "safe" | "warning" | "danger" | "critical" | "recovery";
