// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RadarSourceErrorCode = "timeout" | "upstream_unavailable" | "response_too_large" | "invalid_json" | "contract_violation";
