// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deliberately narrow context whose fields are safe to serialize.
 */
export type SafeErrorContext = { maxBytes: number | null, };
