// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explicit SMTP password mutation. An empty string never means delete.
 */
export type SecretUpdate = "keep" | { "set": string } | "delete";
