// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertPreferenceDraft } from "./AlertPreferenceDraft";
import type { QuotaPolicyDraft } from "./QuotaPolicyDraft";
import type { SecretUpdate } from "./SecretUpdate";
import type { SmtpSettingsDraft } from "./SmtpSettingsDraft";

/**
 * Complete settings replacement submitted against one optimistic revision.
 */
export type SettingsDraft = { expectedSettingsRevision: number, authPath: string | null, quotaPolicy: QuotaPolicyDraft, alertPreferences: Array<AlertPreferenceDraft>, autostartEnabled: boolean, smtp: SmtpSettingsDraft, smtpPassword: SecretUpdate, };
