// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supported SMTP security modes. Plaintext and opportunistic downgrade are
 * intentionally not representable.
 */
export type SmtpTlsMode = "tls" | "starttls";
