// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmtpRecipientDraft } from "./SmtpRecipientDraft";
import type { SmtpTlsMode } from "./SmtpTlsMode";

/**
 * Complete non-secret SMTP settings replacement.
 */
export type SmtpSettingsDraft = { enabled: boolean, host: string, port: number, tlsMode: SmtpTlsMode, username: string, fromAddress: string, fromName: string, recipients: Array<SmtpRecipientDraft>, };
