// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current availability of the SMTP secret without exposing the secret or its
 * credential slot.
 */
export type SmtpCredentialStatus = "configured" | "missing" | "unavailable";
