// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Complete replacement for one recipient row.
 */
export type SmtpRecipientDraft = { address: string, enabled: boolean, };
