// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Freshness state projected alongside the last-known-good observation.
 */
export type SourceFreshness = "fresh" | "stale" | "unavailable";
