// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Complete source state; the UI only localizes this Rust-owned decision.
 */
export type SourceStatus = "fresh" | "stale_after_failure" | "stale_by_age" | "unavailable";
