// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Visual narrative used by the compact quota overview.
 */
export type StoryTheme = "rising_water" | "last_supply_line";
