// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identifier for a visual narrative used by the compact quota overview.
 */
export type StoryTheme = string;
