// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether today's available quota is complete-day accounting or a
 * forward-looking recommendation after an incomplete local baseline.
 */
export type TodayAvailabilityKind = "actual" | "suggested_from_now" | "unavailable";
