// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compact native tray information density.
 */
export type TrayDisplayMode = "wave" | "wave_weekly_remaining" | "wave_reset_countdown";
